In [1]:
import numpy as np
from sklearn.datasets import load_iris

In [2]:
# Load iris data
iris = load_iris()

# Create feature matrix
X = iris.data

# Create target vector
y = iris.target

In [3]:
# Remove first 40 observations
X = X[40:,:] # Da linha 40 até o final, todas as colunas
y = y[40:]

# Create binary target vector indicating if class 0
y = np.where((y == 0), 0, 1) # Onde o y for 0, será 0, senão 1

# Look at the imbalanced target vector
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [4]:
# Indicies of 0 class' observations
i_class0 = np.where(y == 0)[0] #indice dos elementos da classe 0

i_class0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [5]:
# Indicies of 1 class' observations
i_class1 = np.where(y == 1)[0] #indice dos elementos da classe 1

i_class1

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
       101, 102, 103, 104, 105, 106, 107, 108, 109], dtype=int64)

In [6]:
# Number of observations in each class
n_class0 = len(i_class0) #tamanho dos elementos da classe 0

n_class0

10

In [7]:
# Number of observations in each class
n_class1 = len(i_class1) #tamanho dos elementos da classe 1

n_class1

100

In [8]:
# For every observation of class 0, randomly sample from class 1 without replacement
i_class1_downsampled = np.random.choice(i_class1, size=n_class0, replace=False) #seleciona aleatoriomante (random choice)

In [9]:
#seleciona aleatoriamente elementos até ter o tamanho da classe (size=n_class0)
# Se replace igual a True pode-se ter elementos duplicados

# Join together class 0's target vector with the downsampled class 1's target vector
np.hstack((y[i_class0], y[i_class1_downsampled]))# junta os elementos da classe 0 e 1 novamente

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])