## Perceptron In Scikit
<hr />

Link: https://chrisalbon.com/

### Preliminaries

In [1]:
# Load required libraries
#!pip install sklearn
from sklearn import datasets # Carregar banco de dados
from sklearn.preprocessing import StandardScaler # Normalização
from sklearn.linear_model import Perceptron # Rede Neural
from sklearn.model_selection import train_test_split # Separar dados em treino e teste
from sklearn.metrics import accuracy_score # Aferir qualidade do modelo
import numpy as np # Trabalhar com vetores
import pandas as pd

### Load The Iris Data

In [2]:
# Load the iris dataset
iris = datasets.load_iris()

print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

### View The Iris Data

In [3]:
# Create our X and y data
X = iris.data
y = iris.target

pd.DataFrame(X)

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [4]:
# View the first five observations of our y data
y[:5] # Pega todos os y até o 5º elemento

array([0, 0, 0, 0, 0])

In [5]:
# View the first five observations of our x data.
# Notice that there are four independent variables (features)
X[:5] # Pega todos os X até o 5º elemento

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

### Split The Iris Data Into Training And Test

In [6]:
# Split the data into 70% training data and 30% test data
# Separa os dados de treino e teste (30% dos dados)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

pd.DataFrame(X_train)

0    1    2    3
0    4.6  3.2  1.4  0.2
1    6.1  3.0  4.6  1.4
2    5.7  2.6  3.5  1.0
3    6.7  3.0  5.0  1.7
4    5.0  3.4  1.5  0.2
..   ...  ...  ...  ...
100  5.0  2.3  3.3  1.0
101  6.1  2.8  4.0  1.3
102  6.2  2.9  4.3  1.3
103  5.2  3.4  1.4  0.2
104  5.0  3.5  1.6  0.6

[105 rows x 4 columns]

### Preprocess The X Data By Scaling

- Em modelos de ML, não podemos considerar pesos entre as features
- Normalizar é colocar todas as features na mesma faixa de intervalo

In [7]:
# Train the scaler, which standarizes all the features to have mean=0 and unit variance
sc = StandardScaler()
#sc.fit(X_train) # Treina e aprende como normalizar
sc.fit_transform(X_train) # Treina e normaliza

pd.DataFrame(sc.fit_transform(X_train))

0         1         2         3
0   -1.443683  0.275730 -1.242513 -1.236378
1    0.392990 -0.169680  0.575799  0.346789
2   -0.096790 -1.060498 -0.049246 -0.180933
3    1.127659 -0.169680  0.803088  0.742581
4   -0.953904  0.721139 -1.185691 -1.236378
..        ...       ...       ...       ...
100 -0.953904 -1.728612 -0.162890 -0.180933
101  0.392990 -0.615089  0.234865  0.214858
102  0.515434 -0.392384  0.405332  0.214858
103 -0.709014  0.721139 -1.242513 -1.236378
104 -0.953904  0.943844 -1.128869 -0.708656

[105 rows x 4 columns]

In [8]:
# Apply the scaler to the X training data
X_train_std = sc.transform(X_train)

# Apply the SAME scaler to the X test data
X_test_std = sc.transform(X_test)

In [9]:
pd.DataFrame(X_train_std)

0         1         2         3
0   -1.443683  0.275730 -1.242513 -1.236378
1    0.392990 -0.169680  0.575799  0.346789
2   -0.096790 -1.060498 -0.049246 -0.180933
3    1.127659 -0.169680  0.803088  0.742581
4   -0.953904  0.721139 -1.185691 -1.236378
..        ...       ...       ...       ...
100 -0.953904 -1.728612 -0.162890 -0.180933
101  0.392990 -0.615089  0.234865  0.214858
102  0.515434 -0.392384  0.405332  0.214858
103 -0.709014  0.721139 -1.242513 -1.236378
104 -0.953904  0.943844 -1.128869 -0.708656

[105 rows x 4 columns]

### Train A Perceptron Learner

- Perceptron vai treinar 40 vezes
  - eta: pesos

In [10]:
# Create a perceptron object with the parameters: 40 iterations (epochs) over the data, and a learning rate of 0.1
ppn = Perceptron(eta0=0.1, random_state=0) # Instanciando modelo de classificação

# Train the perceptron
ppn.fit(X_train_std, y_train) # Treinando a rede neural

Perceptron(eta0=0.1)

### Apply The Trained Learner To Test Data

In [11]:
# Apply the trained perceptron on the X data to make predicts for the y test data
y_pred = ppn.predict(X_test_std) # Predizer a partir dos meus dados de teste

### Compare The Predicted Y With The True Y

In [12]:
# View the predicted y test data
y_pred # Target previsto a partir da massa de teste

array([1, 2, 2, 1, 0, 0, 2, 1, 2, 1, 2, 2, 1, 0, 1, 1, 1, 0, 1, 2, 2, 0,
       2, 0, 2, 1, 0, 0, 1, 1, 0, 2, 1, 1, 2, 0, 2, 2, 2, 2, 0, 2, 0, 1,
       0])

In [13]:
# View the true y test data
y_test # Target real

array([1, 2, 2, 1, 0, 0, 2, 1, 2, 1, 2, 2, 1, 0, 2, 1, 1, 0, 1, 2, 2, 0,
       2, 1, 2, 1, 0, 1, 1, 1, 0, 2, 1, 2, 2, 0, 2, 2, 2, 2, 0, 2, 0, 1,
       0])

In [14]:
y_pred == y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

### Examine Accuracy Metric

- Acurácia verifica o quanto o modelo (rede neural) acertou
- Função "accuracy_score"

In [15]:
# View the accuracy of the model, which is: 1 - (observations predicted wrong / total observations)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Accuracy: 0.91
