In [1]:
import numpy as np
import pandas as pd

In [2]:
# Create feature matrix
X = np.array([[1.1, 11.1], 
              [2.2, 22.2], 
              [3.3, 33.3], 
              [4.4, 44.4], 
              [np.nan, 55]])

In [3]:
X

array([[ 1.1, 11.1],
       [ 2.2, 22.2],
       [ 3.3, 33.3],
       [ 4.4, 44.4],
       [ nan, 55. ]])

In [8]:
# Retornando X, mas retirando linhas com dados "nan"
X[~np.isnan(X).any(axis=1)]

array([[ 1.1, 11.1],
       [ 2.2, 22.2],
       [ 3.3, 33.3],
       [ 4.4, 44.4]])

In [5]:
np.isnan(X)

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False]])

In [6]:
~np.isnan(X)

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [False,  True]])

In [7]:
~np.isnan(X).any(axis=1)

array([ True,  True,  True,  True, False])